name = "CAIR"
license = "MIT"

tags = ["academic",
        "university",
        "research",
        "publications",
        "widgets",
        "portfolio",
        "responsive",
        "clean",
        "company",
        "blog",
        "events",
        "minimal",
        "light",
        "dark",
        "multilingual",
        "landing page",
        "contact form",
        "mobile",
        "search",
        "presentation",
        "simple",
        "minimalist",
        "starter",
        "modern",
        "one page",
        "customizable",
        "technical",
        "slide"
        ]
features = ["page builder", "widgets", "themes", "search", "research publication system", "filterable portfolio",
            "blog", "create courses", "talks", "events", "slides", "gallery", "contact form"]

[author]
  name = "Brent Farina,Rethabile Modise, Tyron Nyambe"
  homepage = "https://Team-AI-Family"
